bus_administration/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bus_control.urls'))
]

bus_control/urls.py
from django.urls import path 

from .views import (PassagerMasterView, TradeMasterView, HomeView, TradeAddView)

app_name = "bus_control"

urlpatterns = [
    path("", HomeView.as_view() , name = "home"),
    path("passager/", PassagerMasterView.as_view(), name= "passagers"),
    path("trades/", TradeMasterView.as_view() , name = "trades_master"),
    path("trades/add", TradeAddView.as_view() , name = "trades_add"),
]

bus_control/models/bus.py
from django.db import models

class Bus(models.Model):
    serial = models.CharField(max_length=50, unique=True)
    lotacao = models.IntegerField()

    def __str__(self):
        return f"Serial: {self.serial}\nLotação: {self.lotacao}"

bus_control/models/passage.py
from django.db import models
from djmoney.models.fields import MoneyField
from .passager import (Passager)
from .travel import (Travel)

class Passage(models.Model):
    passager = models.ForeignKey(Passager, verbose_name="Passager", on_delete=models.CASCADE)
    travel = models.ForeignKey(Travel, verbose_name="Travel", on_delete=models.CASCADE)
    price = MoneyField(max_digits=19, decimal_places=2, default_currency="BRL")

    def __str__(self):
        return f"{self.passager} {self.price}"
    

bus_control/models/passager.py
from django.db import models

class Passager(models.Model):
    name = models.CharField(max_length=150)
    document = models.CharField(max_length=11)

    def __str__(self):
        return f"Name: {self.name}\nDocument: {self.document}"

bus_control/models/route.py
from django.db import models

class Route(models.Model):
    origem = models.CharField(max_length=50,)
    destiny = models.CharField(max_length=50)

    def __str__(self):
        return f"Origem: {self.origem}\nDestiny: {self.destiny}"

bus_control/models/trade.py
from django.db import models
from djmoney.models.fields import MoneyField
from . import (Passage)

class Trade(models.Model):
    date = models.DateTimeField(auto_now=False, auto_now_add=False)
    total = MoneyField(max_digits=19, decimal_places=2, default_currency="BRL")
    passages = models.ManyToManyField(Passage)

    

bus_control/models/travel.py
from django.db import models
from .route import (Route)
from .bus import (Bus)

class Travel(models.Model):
    date = models.DateTimeField(auto_now=False, auto_now_add=False)
    route = models.ForeignKey(Route, verbose_name="Route", on_delete=models.CASCADE)
    bus = models.ForeignKey(Bus, verbose_name="Bus", on_delete=models.CASCADE)

bus_control/forms.py
from django.forms import ModelForm
from django.forms import DateTimeField
from django.utils.dateparse import datetime 
from djmoney.forms import MoneyWidget

from .models import Trade, Passage

class TradeForm(ModelForm):
    date = DateTimeField(initial=datetime.datetime.now())
    class Meta:
        model = Trade
        fields = "__all__"

bus_control/views.py
from django.shortcuts import render, redirect, resolve_url
from django.views.generic import View, CreateView

from .models import Passager, Trade

# Create your views here.

class HomeView(View):
    def get(self, request):
        return redirect("bus_control:trades_master")

class PassagerMasterView(View):
    template_name = "bus_control/passager_master.html"
    def get(self, request):
        passagers = Passager.objects.all()
        return render(request, self.template_name, context={"passagers": passagers})

class TradeMasterView(View):
    template_name = "bus_control/trades_master.html"
    def get(self, request):
        trades = Trade.objects.all()
        return render(request, self.template_name, context={"trades": trades})

class TradeAddView(CreateView):
    model = Trade
    fields = [
        "date",
        "passages",
        "total",
    ]

bus_control/templates/bus_control/passager_master.html
<div>
<p> Its working, Passager! </p>
</br>
{% for passager in passagers %}
<p>{{passager}}</p>
{% endfor %}
</div>

bus_control/templates/bus_control/trade_form.html
<form action="{% url 'bus_control:trades_add' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>

bus_control/templates/bus_control/trades_master.html
{% load static %}
<head>
    <link rel="stylesheet" href="{% static 'bus_control/css/style.css' %}"
</head>
<body>
<div>
    <h1 id="page_title">Trades</h1>
    {% for trade in trades %}
    <div class="trade">
        <p>
        {{trade.id}}
        </p>
        <p>
        {{trade.total}}
        {{trade.date}}
        <p>
        {% for passage in trade.passages.all %}
        <div class="passage">
            <p> 
                {{passage.passager}}
            </p>
            <p>
                {{passage.price}}
            </p>
            <p>
                {{passage.travel.route}}
            </p>
            <p>
                {{passage.travel.bus}}
            </p>
            <p>
                {{passage.travel.date}}
            </p>
        </div>
        {% endfor %}
    </div>
    {% endfor %}
</div>
</body>